# Generated by Django 5.2.1 on 2025-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_about_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='img3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
